server:
  port: 8082
spring:
  application:
    name: rabbit-consumer
  rabbitmq:
    host: 192.168.190.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /admin
    #消息发送确认回调
    publisher-confirms: true
    #指定消息确认模式为手动确认
    listener:
      simple:
        acknowledge-mode: manual
    #发送返回监听回调
    publisher-returns: true