server:
  port: 8090
spring:
  application:
    name: index-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/,http://localhost:10001/eureka/
    registry-fetch-interval-seconds: 30  #每隔30秒抓取一次新的注册信息
  instance:
  #客户端实例每隔30秒向服务端发送心跳
    lease-renewal-interval-in-seconds: 30
    #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，
    #在这个时间内若没收到下一次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 90


#结合feign开启熔断机制
feign:
  hystrix:
    enabled: true
#配置压缩，提高性能
#Spring Cloud Feign 支持对请求和响应进行GZIP压缩，以减少通信过程中的性能损耗
  compression:
    request:
      enabled: true
    response:
      enabled: true


logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: "*"





