server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/gh?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.gh.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug